# Generated by Django 4.2 on 2024-06-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category', 'price'], 'permissions': [('can_edit_published', 'Активация публикации'), ('can_change_description', 'Изменить описание'), ('can_change_category', 'Изменить категорию')], 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='owner',
        ),
    ]
